In [1]:
import numpy as np

In [2]:
list_=['1','2','3','4','5']

In [3]:
array_list=np.array(list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [7]:
# Q1. Is there any difference in the data type of variables list_ and 
# array_list? If there is then write a code to print the data types 
# of both the variables.

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [11]:
# Q2. Write a code to print the data type of each and every element of both 
# the variables list_ and array_list.

for i in array_list:
    print(type(array_list[0]));

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [12]:
for i in list_:
    print(type(i));

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [17]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present 
# in both the variables, list_ and array_list? If so then print the data 
# types of each and every element present in both the variables, list_
# and arra_list.


''' Yes datatype of list is 'str' and array_list is int '''

In [19]:
for i in list_:
    print(type(i));

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [20]:
for i in array_list:
    print(type(array_list[0]));

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [22]:
# Q4 .Consider the below code to answer further questions:
# import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#  Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size



In [23]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [24]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
num_array.shape

(2, 3)

In [29]:
num_array.size

6

In [32]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros 
# only, using a numpy array creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and 
# other elements will be 0.]

np.eye(5,5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])