In [21]:
# used for advance mathematical computation

In [351]:
import numpy as np

In [352]:
l=[1,2,3,4,5];

ar=np.array(l) #converting list to array

In [353]:
type(l)

list

In [354]:
type(ar)

numpy.ndarray

In [355]:
ar

array([1, 2, 3, 4, 5])

In [356]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [357]:
a=[2,3,4]


In [358]:
b=np.matrix(a)

In [359]:
b

matrix([[2, 3, 4]])

In [360]:
np.array(b)

array([[2, 3, 4]])

In [361]:
np.asanyarray(b)

matrix([[2, 3, 4]])

In [362]:
b=np.array([1,2,3])

In [363]:
b

array([1, 2, 3])

In [364]:
c=b #[pass by refrence ] swallow copy

In [365]:
c[0]=100

In [366]:
c

array([100,   2,   3])

In [367]:
b

array([100,   2,   3])

In [368]:
d=np.copy(a)  #swallow copy

In [369]:
d

array([2, 3, 4])

In [370]:
a

[2, 3, 4]

In [371]:
d[1]=100

In [372]:
d

array([  2, 100,   4])

In [373]:
a

[2, 3, 4]

In [374]:
np.fromfunction(lambda x,y:x==y ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [375]:
np.fromfunction(lambda x,y :x*y,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [376]:
iterable=(i*i for i in range(5))
    

In [377]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [378]:
np.fromstring('123 445 54', sep=' ')

array([123., 445.,  54.])

In [379]:

#data types

In [380]:
l=[1,2,3,4]

In [381]:
a=np.array(l)

In [382]:
a

array([1, 2, 3, 4])

In [383]:
a.ndim

1

In [384]:
ar2=np.array([[1,2,3,4],[4,56,7,8]])

In [385]:
ar2

array([[ 1,  2,  3,  4],
       [ 4, 56,  7,  8]])

In [386]:
type(ar2)

numpy.ndarray

In [387]:
ar2.ndim

2

In [388]:
ar.size

5

In [389]:
ar2.size

8

In [390]:
ar.shape

(5,)

In [391]:
ar2.shape

(2, 4)

In [392]:
ar.dtype

dtype('int32')

In [393]:
c=np.array([1,"2","4","5"])

In [394]:
c

array(['1', '2', '4', '5'], dtype='<U11')

In [395]:
c.dtype

dtype('<U11')

In [396]:
# lets making a float point list using arange

In [397]:
list(np.arange(0.2,5.6,0.3))  # (start,end,jump)

[0.2,
 0.5,
 0.8,
 1.0999999999999999,
 1.4,
 1.7,
 1.9999999999999998,
 2.3000000000000003,
 2.6,
 2.9,
 3.2,
 3.5,
 3.8,
 4.1,
 4.4,
 4.7,
 5.0,
 5.3]

In [398]:
np.linspace(1,5,10) # s e and no.of data

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [399]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [400]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [401]:
np.zeros((3,2,3))#3d array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [402]:
np.zeros((3,2,3)).ndim 

3

In [403]:
n=np.ones((4,5),int) # by default it takes float

In [404]:
n

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [405]:
n+4

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [406]:
n*4

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [407]:
np.empty((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [408]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [409]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [410]:
np.logspace(2,4,20,base=2)

array([ 4.        ,  4.30276234,  4.62844095,  4.97877036,  5.3556164 ,
        5.76098615,  6.19703857,  6.66609605,  7.17065677,  7.71340798,
        8.29724036,  8.92526334,  9.60082176, 10.32751358, 11.10920914,
       11.95007169, 12.85457963, 13.82755029, 14.87416568, 16.        ])

In [411]:
arr=np.random.randn(3,4) 

In [412]:
import pandas as pd

In [413]:
pd.DataFrame(arr)

0         1         2         3
0 -0.220806  0.606223  0.636186  0.750985
1 -0.302606 -0.354665 -0.933702 -0.351702
2  0.123832 -1.287184 -2.171858  1.274167

In [414]:
a=np.random.rand(3,4)

In [415]:
a

array([[0.64451052, 0.98665135, 0.3600338 , 0.81968246],
       [0.05679097, 0.51747237, 0.13043846, 0.75607439],
       [0.92180676, 0.66472971, 0.45483928, 0.87215783]])

In [416]:
pd.DataFrame(arr)

0         1         2         3
0 -0.220806  0.606223  0.636186  0.750985
1 -0.302606 -0.354665 -0.933702 -0.351702
2  0.123832 -1.287184 -2.171858  1.274167

In [747]:
l=np.random.randint(1,10,(2,4))

In [748]:
l

array([[5, 1, 5, 7],
       [2, 6, 6, 1]])

In [749]:
a=pd.DataFrame(l)

In [750]:
a

0  1  2  3
0  5  1  5  7
1  2  6  6  1

In [751]:
import csv
a.to_csv("t.csv")

In [752]:
ar=np.random.rand(3,4)

In [753]:
ar

array([[0.24773496, 0.57549419, 0.56230096, 0.83945989],
       [0.86268408, 0.32611311, 0.15944202, 0.92792522],
       [0.88960594, 0.79814741, 0.65257815, 0.45520441]])

In [754]:
ar.reshape(4,3)

array([[0.24773496, 0.57549419, 0.56230096],
       [0.83945989, 0.86268408, 0.32611311],
       [0.15944202, 0.92792522, 0.88960594],
       [0.79814741, 0.65257815, 0.45520441]])

In [425]:
arr1=ar.transpose()

In [426]:
arr1

array([[0.66441719, 0.71099288, 0.12006706],
       [0.5621853 , 0.25285653, 0.87476648],
       [0.77709347, 0.58314246, 0.83397311],
       [0.541198  , 0.73246828, 0.59459978]])

In [427]:
arr1[2,2]

0.8339731095319953

In [428]:
arr1[1,1]

0.2528565311330744

In [429]:
arr1[1][1]

0.2528565311330744

In [430]:
arr1[2][2]

0.8339731095319953

In [431]:
arr1[1]

array([0.5621853 , 0.25285653, 0.87476648])

In [432]:
arr1[0:4,1]

array([0.71099288, 0.25285653, 0.58314246, 0.73246828])

In [433]:
arr=np.random.randint(1,10,(5,5))

In [434]:
arr

array([[9, 6, 9, 1, 8],
       [2, 5, 7, 7, 4],
       [6, 7, 3, 5, 3],
       [9, 2, 2, 2, 1],
       [4, 5, 8, 9, 4]])

In [435]:
arr[arr>3]

array([9, 6, 9, 8, 5, 7, 7, 4, 6, 7, 5, 9, 4, 5, 8, 9, 4])

In [436]:
arr

array([[9, 6, 9, 1, 8],
       [2, 5, 7, 7, 4],
       [6, 7, 3, 5, 3],
       [9, 2, 2, 2, 1],
       [4, 5, 8, 9, 4]])

In [437]:
arr[2:4,1:3]

array([[7, 3],
       [2, 2]])

In [438]:
arr[0][0]=78 #manipulation

In [439]:
arr

array([[78,  6,  9,  1,  8],
       [ 2,  5,  7,  7,  4],
       [ 6,  7,  3,  5,  3],
       [ 9,  2,  2,  2,  1],
       [ 4,  5,  8,  9,  4]])

In [440]:
arr1=np.random.randint(1,3,(3,3));
arr2=np.random.randint(1,3,(3,3));

In [441]:
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1]])

In [442]:
arr2

array([[2, 2, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [443]:
arr1+arr2

array([[3, 3, 3],
       [3, 2, 3],
       [3, 4, 2]])

In [444]:
arr1-arr2

array([[-1, -1, -1],
       [ 1,  0,  1],
       [-1,  0,  0]])

In [445]:
arr1/arr2

array([[0.5, 0.5, 0.5],
       [2. , 1. , 2. ],
       [0.5, 1. , 1. ]])

In [446]:
arr1*arr2 #normal multiplication

array([[2, 2, 2],
       [2, 1, 2],
       [2, 4, 1]])

In [447]:
arr1                             

array([[1, 1, 1],
       [2, 1, 2],
       [1, 2, 1]])

In [448]:
arr1@arr2 #matrix multiplication

array([[5, 5, 4],
       [9, 9, 7],
       [6, 6, 5]])

In [449]:
arr1/0

C:\Users\el091\AppData\Local\Temp\ipykernel_6540\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [450]:
arr1+100

array([[101, 101, 101],
       [102, 101, 102],
       [101, 102, 101]])

In [451]:
arr1**2

array([[1, 1, 1],
       [4, 1, 4],
       [1, 4, 1]], dtype=int32)

In [452]:
arr=np.zeros((4,4))

In [453]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [454]:
row=np.array([1,2,3,4])

In [455]:
row

array([1, 2, 3, 4])

In [456]:
row+arr #broadcat row wise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [457]:
col=np.array([[1,2,3,4]])

In [458]:
col=col.T #transpose

In [459]:
col+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [460]:
arr1=np.random.randint(1,4,(3,4))

In [461]:
arr1

array([[2, 3, 1, 3],
       [1, 1, 3, 2],
       [3, 1, 2, 1]])

In [462]:
np.sqrt(arr1)

array([[1.41421356, 1.73205081, 1.        , 1.73205081],
       [1.        , 1.        , 1.73205081, 1.41421356],
       [1.73205081, 1.        , 1.41421356, 1.        ]])

In [463]:
np.exp(arr1)

array([[ 7.3890561 , 20.08553692,  2.71828183, 20.08553692],
       [ 2.71828183,  2.71828183, 20.08553692,  7.3890561 ],
       [20.08553692,  2.71828183,  7.3890561 ,  2.71828183]])

In [464]:
np.log10(arr1)

array([[0.30103   , 0.47712125, 0.        , 0.47712125],
       [0.        , 0.        , 0.47712125, 0.30103   ],
       [0.47712125, 0.        , 0.30103   , 0.        ]])

In [465]:
np.square(arr1)

array([[4, 9, 1, 9],
       [1, 1, 9, 4],
       [9, 1, 4, 1]], dtype=int32)

In [466]:
#chapter 2

In [643]:
arr=np.random.randint(1,10,(3,4))

In [644]:
arr

array([[6, 6, 1, 6],
       [5, 9, 2, 1],
       [4, 5, 1, 3]])

In [645]:
arr.reshape(6,2)

array([[6, 6],
       [1, 6],
       [5, 9],
       [2, 1],
       [4, 5],
       [1, 3]])

In [646]:
arr.T

array([[6, 5, 4],
       [6, 9, 5],
       [1, 2, 1],
       [6, 1, 3]])

In [647]:
arr.T.T

array([[6, 6, 1, 6],
       [5, 9, 2, 1],
       [4, 5, 1, 3]])

In [648]:
arr.flatten()

array([6, 6, 1, 6, 5, 9, 2, 1, 4, 5, 1, 3])

In [649]:
arr.reshape(1,12)

array([[6, 6, 1, 6, 5, 9, 2, 1, 4, 5, 1, 3]])

In [650]:
arr1=np.array([1,2,3,3,4])

In [651]:
arr1

array([1, 2, 3, 3, 4])

In [652]:
arr1.ndim

1

In [653]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [654]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 3, 4]])

In [655]:
arr

array([[6, 6, 1, 6],
       [5, 9, 2, 1],
       [4, 5, 1, 3]])

In [656]:
data= np.array([[1],[2],[3]])

In [657]:
data

array([[1],
       [2],
       [3]])

In [658]:
np.squeeze(data)

array([1, 2, 3])

In [659]:
arr

array([[6, 6, 1, 6],
       [5, 9, 2, 1],
       [4, 5, 1, 3]])

In [660]:
np.repeat(arr,2)

array([6, 6, 6, 6, 1, 1, 6, 6, 5, 5, 9, 9, 2, 2, 1, 1, 4, 4, 5, 5, 1, 1,
       3, 3])

In [661]:
arr1

array([1, 2, 3, 3, 4])

In [662]:
np.roll(arr1,2) #rotation by 2

array([3, 4, 1, 2, 3])

In [663]:
arr1

array([1, 2, 3, 3, 4])

In [664]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [665]:
#Numpy Binary operation

In [666]:
arr1

array([1, 2, 3, 3, 4])

In [667]:
arr2=np.random.randint(1,10,(3,4))

In [668]:
arr2

array([[1, 1, 2, 7],
       [7, 3, 4, 3],
       [2, 8, 1, 2]])

In [669]:
arr

array([[6, 6, 1, 6],
       [5, 9, 2, 1],
       [4, 5, 1, 3]])

In [670]:
arr2+arr

array([[ 7,  7,  3, 13],
       [12, 12,  6,  4],
       [ 6, 13,  2,  5]])

In [671]:
arr%arr2

array([[0, 0, 1, 6],
       [5, 0, 2, 1],
       [0, 5, 0, 1]], dtype=int32)

In [672]:
arr^arr2

array([[ 7,  7,  3,  1],
       [ 2, 10,  6,  2],
       [ 6, 13,  0,  1]], dtype=int32)

In [580]:
arr**arr2

array([[      7,   16807,    6561,    4096],
       [     81,  262144,     512,       1],
       [2097152,     343,       1,   46656]], dtype=int32)

In [585]:
arr2

array([[1, 5, 8, 4],
       [2, 6, 9, 4],
       [7, 3, 7, 6]])

In [584]:
arr

array([[7, 7, 3, 8],
       [9, 8, 2, 1],
       [8, 7, 1, 6]])

In [582]:
arr & arr2

array([[1, 5, 0, 0],
       [0, 0, 0, 0],
       [0, 3, 1, 6]], dtype=int32)

In [590]:
~arr

array([[ -8,  -8,  -4,  -9],
       [-10,  -9,  -3,  -2],
       [ -9,  -8,  -2,  -7]], dtype=int32)

In [588]:
arr | arr2

array([[ 7,  7, 11, 12],
       [11, 14, 11,  5],
       [15,  7,  7,  6]], dtype=int32)

In [591]:
arr>arr2

array([[ True,  True, False,  True],
       [ True,  True, False, False],
       [ True,  True, False, False]])

In [593]:
arr[arr>arr2]

array([7, 7, 8, 9, 8, 8, 7])

In [ ]:
arr

In [594]:
#String in numpy

In [600]:
arr=np.array(["akshir" ,"raza"])

In [601]:
arr

array(['akshir', 'raza'], dtype='<U6')

In [602]:
np.char.upper(arr)

array(['AKSHIR', 'RAZA'], dtype='<U6')

In [603]:
np.char.title(arr)

array(['Akshir', 'Raza'], dtype='<U6')

In [604]:
np.char.capitalize(arr)

array(['Akshir', 'Raza'], dtype='<U6')

In [611]:
#MAths

In [612]:
arr2

array([[1, 5, 8, 4],
       [2, 6, 9, 4],
       [7, 3, 7, 6]])

In [613]:
np.sin(arr2)

array([[ 0.84147098, -0.95892427,  0.98935825, -0.7568025 ],
       [ 0.90929743, -0.2794155 ,  0.41211849, -0.7568025 ],
       [ 0.6569866 ,  0.14112001,  0.6569866 , -0.2794155 ]])

In [614]:
np.cos(arr2)

array([[ 0.54030231,  0.28366219, -0.14550003, -0.65364362],
       [-0.41614684,  0.96017029, -0.91113026, -0.65364362],
       [ 0.75390225, -0.9899925 ,  0.75390225,  0.96017029]])

In [615]:
np.tan(arr2)

array([[ 1.55740772, -3.38051501, -6.79971146,  1.15782128],
       [-2.18503986, -0.29100619, -0.45231566,  1.15782128],
       [ 0.87144798, -0.14254654,  0.87144798, -0.29100619]])

In [625]:
np.log2(arr2)

array([[0.        , 2.32192809, 3.        , 2.        ],
       [1.        , 2.5849625 , 3.169925  , 2.        ],
       [2.80735492, 1.5849625 , 2.80735492, 2.5849625 ]])

In [626]:
np.power(arr2,2)

array([[ 1, 25, 64, 16],
       [ 4, 36, 81, 16],
       [49,  9, 49, 36]], dtype=int32)

In [627]:
np.mean(arr2)

5.166666666666667

In [630]:
np.median(arr2)

5.5

In [631]:
np.std(arr2)

2.3392781412696997

In [634]:
np.min(arr2)

1

In [635]:
np.max(arr2)

9

In [636]:
arr2

array([[1, 5, 8, 4],
       [2, 6, 9, 4],
       [7, 3, 7, 6]])

In [673]:
#Sort,Search and Counting Function

In [674]:
arr

array([[6, 6, 1, 6],
       [5, 9, 2, 1],
       [4, 5, 1, 3]])

In [677]:
arr=arr.flatten()

In [690]:
arr

array([6, 6, 1, 6, 5, 9, 2, 1, 4, 5, 1, 3])

In [691]:
np.size(arr)

12

In [692]:
np.sort(arr)

array([1, 1, 1, 2, 3, 4, 5, 5, 6, 6, 6, 9])

In [693]:
np.searchsorted(arr,8)

12

In [694]:
arr1=np.array([3,344,3,0,0,0,45,45,5,65,5,7,67,4])

In [695]:
np.count_nonzero(arr1)

11

In [696]:
arr1

array([  3, 344,   3,   0,   0,   0,  45,  45,   5,  65,   5,   7,  67,
         4])

In [700]:
np.where(arr1>6)

(array([ 1,  6,  7,  9, 11, 12], dtype=int64),)

In [702]:
np.extract(arr1>6,arr1)

array([344,  45,  45,  65,   7,  67])

In [703]:
arr1

array([  3, 344,   3,   0,   0,   0,  45,  45,   5,  65,   5,   7,  67,
         4])

In [704]:
#Numpy Byte swapping

In [705]:
arr

array([6, 6, 1, 6, 5, 9, 2, 1, 4, 5, 1, 3])

In [706]:
arr.byteswap()

array([100663296, 100663296,  16777216, 100663296,  83886080, 150994944,
        33554432,  16777216,  67108864,  83886080,  16777216,  50331648])

In [707]:
#Numpy Copy and Views

In [722]:
arr

array([67,  6,  1,  6,  5,  9,  2,  1,  4,  5,  1,  3])

In [723]:
a=np.copy(arr) #deep copy

In [724]:
b=arr.view() #swallow copy

In [725]:
b

array([67,  6,  1,  6,  5,  9,  2,  1,  4,  5,  1,  3])

In [726]:
b[0]=67

In [727]:
b

array([67,  6,  1,  6,  5,  9,  2,  1,  4,  5,  1,  3])

In [728]:
arr

array([67,  6,  1,  6,  5,  9,  2,  1,  4,  5,  1,  3])

In [729]:
a

array([67,  6,  1,  6,  5,  9,  2,  1,  4,  5,  1,  3])

In [730]:
a[0]=56

In [731]:
a

array([56,  6,  1,  6,  5,  9,  2,  1,  4,  5,  1,  3])

In [732]:
arr

array([67,  6,  1,  6,  5,  9,  2,  1,  4,  5,  1,  3])

In [741]:
#Numpy Matrix Library

In [742]:
import numpy.matlib as nm

In [743]:
nm.zeros(3)

matrix([[0., 0., 0.]])

In [744]:
nm.ones(4,int)

matrix([[1, 1, 1, 1]])

In [745]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [746]:
pwd

'C:\\Users\\el091\\PYTHON'